### ISSUE TITLE
Test failures against pygit2 1.2.1

### ISSUE THREAD

**Issue by risicle** [alpernebbi/git-annex-adapter#14]
Some fairly trivial errors occur when running the tests using pygit2 1.2.1:

```
ERROR: test_file_tree (tests.test_repo.TestGitAnnexRepoOnThreeFiles) (file='foo')
Flat AnnexedFileTree should be correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_repo.py", line 40, in test_file_tree
    self.assertEqual(tree[f].key, k)
AttributeError: '_pygit2.Blob' object has no attribute 'key'

======================================================================
ERROR: test_file_tree (tests.test_repo.TestGitAnnexRepoOnThreeFiles) (file='bar')
Flat AnnexedFileTree should be correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_repo.py", line 40, in test_file_tree
    self.assertEqual(tree[f].key, k)
AttributeError: '_pygit2.Blob' object has no attribute 'key'

======================================================================
ERROR: test_file_tree (tests.test_repo.TestGitAnnexRepoOnThreeFiles) (file='baz')
Flat AnnexedFileTree should be correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_repo.py", line 40, in test_file_tree
    self.assertEqual(tree[f].key, k)
AttributeError: '_pygit2.Blob' object has no attribute 'key'
```

due to some API deprecation I assume.

**Comment by alpernebbi** [comment]
I'm think [`a557422`](https://github.com/alpernebbi/git-annex-adapter/commit/a557422c1c7be05d7eec753ad3bf9ff200cc3822) ("Fix pygit2 objects not being recognized properly") was fixing this (already in v0.2.2).
