### ISSUE TITLE
ImportError when used with git-annex 8.20210223-1~ndall+1

### ISSUE THREAD

**Issue by willmerae** [alpernebbi/git-annex-adapter#16]
NeuroDebian have made a new release of git-annex-standalone, 8.20210223-1~ndall+1. This version string breaks the version detection in git_annex_adapter/__init.py

```
Traceback (most recent call last):
  File ".../git_annex_adapter/__init__.py", line 56, in <module>
    git_annex_version = float(version_str)
ValueError: could not convert string to float: '8.20210223-1~ndall+1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./repo-mirror/git-annex-aware-repo-server.py", line 32, in <module>
    from git_annex_adapter.exceptions import NotAGitAnnexRepoError
  File ".../git_annex_adapter/__init__.py", line 59, in <module>
    msg = fmt.format(git_annnex_version)
NameError: name 'git_annnex_version' is not defined
```

Pull request imminent

**Comment by alpernebbi** [comment]
Thanks for the patch.

I can make a new release with this if you need one, otherwise I'll probably not.

**Comment by willmerae** [comment]
Thanks, I'm not in a rush. Release can wait on your convenience.
