### ISSUE TITLE
[bug] Version parsing does not support "+git" versions

### ISSUE THREAD

**Issue by NGenetzky** [alpernebbi/git-annex-adapter#8]
```
Python 3.7.0 (default, Sep  5 2018, 03:25:31) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import git_annex_adapter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/git_annex_adapter/__init__.py", line 50, in <module>
    git_annex_version = float(version_str.split('-g', 1)[0])
ValueError: could not convert string to float: '6.20181011+git124'
>>> import os
>>> os.system('git-annex version')
git-annex version: 6.20181011+git124-g94aa0e2f6-1~ndall+1
build flags: Assistant Webapp Pairing S3(multipartupload)(storageclasses) WebDAV Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.19 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.2 feed-1.0.0.0 ghc-8.2.2 http-client-0.5.12 persistent-sqlite-2.8.1.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external
operating system: linux x86_64
supported repository versions: 3 5 6
upgrade supported from repository versions: 0 1 2 3 4 5
0
```

**Comment by alpernebbi** [comment]
Sorry for responding a bit late.

Isn't this the same as #5? I think you are still having the error because I haven't tagged and uploaded a newer release to PyPI yet. I should, but I'm busy with some other problems right now.

**Comment by NGenetzky** [comment]
My apologies. I turned a quarter of a century old today and I think the age is starting to hurt my memory.

Thanks for fixing.
